### ISSUE TITLE
请问这个适不适合加载大量数据？

### ISSUE THREAD

**Issue by Brances** [yoonzm/react-native-alphabet-flat-list#1]
如果数据量超过上千条或者更多的情况下，一次性渲染肯定是不行的，如果是分页加载的话，比如第一次加载100条数据，会渲染100个item,第二次再次加载100条数据，是不是会渲染200个item？(就是把之前那100个item也会重新渲染)

**Comment by yoonzm** [comment]
@Brances 使用FlatList就是为了解决一次性显示过多数据导致渲染过慢的问题，目前首次渲染只会显示一屏的数据，所以会特别快。

**Comment by yoonzm** [comment]
@Brances 截图中的数据是大于五百条的，不会有任何的卡顿。使用的时候你不用关注渲染的细节，只需要将需要展示的数据填充进去即可。

**Comment by Brances** [comment]
@yoonzm  谢谢了 ，flatlist比普通的view性能还是优化了不少
