### ISSUE TITLE
Slow scrolling while changing index on iOS

### ISSUE THREAD

**Issue by usamaazam10** [yoonzm/react-native-alphabet-flat-list#3]
On iOS when the pan gesture started on indexes, then this is not scrolling fast. But when pan gesture reached to some specific index it scroll very fast to that section. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/30794533/62708027-f1769d80-ba0b-11e9-9919-fb3dd761749a.gif)

**Comment by yoonzm** [comment]
How many data?
Can you provide example?

**Comment by yoonzm** [comment]
@usamaazam10 
![image](https://user-images.githubusercontent.com/22367929/63423537-17a23180-c43f-11e9-9757-54979dda9dd7.png)
if you need scroll fast, you can modify the delay time, but it may be stuck.
